from setuptools import setup, find_packages

setup(
    name="appian",
    version="0.1",
    author="Arya Sikder",
    author_email="aryasikder17@gmail.com",
    description="A web application for AI-driven code analysis and improvement.",
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url="https://github.com/valiant-disciple/appian",
    packages=find_packages(),
    install_requires=[
        'accelerate==1.0.1',
        'actionlib==1.14.0',
        'aenum==3.1.15',
        'aioboto3==13.3.0',
        'aiobotocore==2.16.0',
        'aiofiles==24.1.0',
        'aiohttp==3.9.5',
        'aioitertools==0.12.0',
        'aiosignal==1.3.1',
        'altair==5.5.0',
        'beautifulsoup4==4.12.3',
        'boto3==1.35.81',
        'botocore==1.35.81',
        'click==8.1.8',
        'fastapi==0.115.6',
        'Flask==3.1.0',
        'numpy==1.26.4',
        'pandas==2.2.1',
        'requests==2.28.1',
        'scikit-learn==1.5.2',
        'streamlit==1.41.1',
        'torch==2.2.2',
        'transformers==4.45.2',
        'uvicorn==0.34.0',
        'Werkzeug==3.1.3',
    ],
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.6',
)